# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl: /gopal-blog.github.io
url: https://raw.githubusercontent.com/gopal-blog/gopal-blog.github.io
date_format: "ordinal"
title: दीपक (Gopal) दुबे ·(Deepak's Blog)
subtitle: "Blog website for Computer Science"
description: "Personal Blog"
keywords: Diary, Deepak, Gopal Mani, Techonlogy, github pages, Post, North America, Leetcode, Interview
timezone: India/Kolkata
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: deepakdubeygi@gmail.com
organization: gopal-blog
organization_url: https://github.com/gopal-blog/
github_username: gopalmani
location: Delhi, India
email: deepakdubeygi@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Home

  -
    href: /categories/
    label: Categories

  -
    href: /open-source/
    label: Github Repos

  -
    href: /about/
    label: About

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
    - jekyll-seo-tag

repository: https://github.com/gopal-blog/gopal-blog.github.io/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# https://disqus.com
disqus:
    username: disqus_UD0C5GALDB
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: gopalmani
    repo: gopalmani.github.io
    oauth:
        clientID: b3ff6fcdc7b2e34fd0c4
        clientSecret: 9dd38c6ce3586ec5d3d1cb415f6d532aec31388b
        # client_id: e32f616bce7761a5d65a
        # client_secret: 309993e00a0bc0e9743c41abbff753f220dff953
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: gopalmani
    repo: gopalmai.github.io
    clientID: b3ff6fcdc7b2e34fd0c4  
    clientSecret: 9dd38c6ce3586ec5d3d1cb415f6d532aec31388b
    # clientID: 4cef70907f5b36353d59
    # clientSecret: 94b120bec4f51b07c796df03ad3ece5a99f71ed6
# Show other comment components when in use Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # Whether support full text search
    fulltext: false
    # Most displayed number of search results
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: G-Y9YNMHJFRH
